org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2

# When updating minecraft version is necessary to update:
# fzmm.zailer.me.client.command.argument_type.VersionArgumentType#initVersions
# fzmm.zailer.me.utils.FzmmWikiConstants
# resources/resourcepacks/fzmm_default_heads/pack.mcmeta

# TODO: look if there is a way for pack format version to be assigned automatically,
# since the pack format version should not affect vanilla (because is a FZMM resource pack),
# and it can be especially annoying when there are things like 1.21.6 and 1.21.7,
# compatible versions but with different pack format version

# Mod Properties
mod_version=0.2.20
maven_group=zailer.me
archives_base_name=fzmm

# Dependencies
# https://fabricmc.net/develop/
fabric_version=0.132.0+1.21.8
# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib
owo_version=0.12.22+1.21.8
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=15.0.0-beta.3
# https://modrinth.com/mod/placeholder-api
placeholder_api_version=2.7.1+1.21.6

# Optional dependencies
# https://modrinth.com/mod/symbol-chat/versions
symbol_chat_version=1.3.7
symbol_chat_reconfigure_version=0.1.13